Traceback (most recent call last):
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import lacell as lac
transcriptome = lac.transcriptome.Transcriptome.from_adata(adata)
transcriptome.plot()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_727273/2511633849.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mlacell[0m [0;32mas[0m [0mlac[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mtranscriptome[0m [0;34m=[0m [0mlac[0m[0;34m.[0m[0mtranscriptome[0m[0;34m.[0m[0mTranscriptome[0m[0;34m.[0m[0mfrom_adata[0m[0;34m([0m[0madata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mtranscriptome[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/projects/probabilistic-cell/lacell/src/lacell/transcriptome/transcriptome.py[0m in [0;36mfrom_adata[0;34m(cls, adata, *args, **kwargs)[0m
[1;32m    179[0m         """
[1;32m    180[0m         return cls(
[0;32m--> 181[0;31m             [0madata[0m[0;34m.[0m[0mraw[0m[0;34m[[0m[0madata[0m[0;34m.[0m[0mobs[0m[0;34m.[0m[0mindex[0m[0;34m,[0m [0madata[0m[0;34m.[0m[0mvar[0m[0;34m.[0m[0mindex[0m[0;34m][0m[0;34m.[0m[0mX[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    182[0m             [0madata[0m[0;34m.[0m[0mobs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    183[0m             [0madata[0m[0;34m.[0m[0mvar[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable

