Traceback (most recent call last):
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/wsaelens/projects/probabilistic-cell/.venv/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, (ax0, ax1) = plt.subplots(1, 2, figsize = (10, 5))
cell_order = model_gs.find("x").prior_pd().sort_values().index
sns.heatmap(observation_value.loc[cell_order], ax = ax0)
modelled_value = observed.samples[observation.p].sel(sample = 0).to_pandas()
sns.heatmap(modelled_value.loc[cell_order], ax = ax1)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_2698258/2466115458.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mcell_order[0m [0;34m=[0m [0mmodel_gs[0m[0;34m.[0m[0mfind[0m[0;34m([0m[0;34m"x"[0m[0;34m)[0m[0;34m.[0m[0mprior_pd[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0msort_values[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mindex[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0msns[0m[0;34m.[0m[0mheatmap[0m[0;34m([0m[0mobservation_value[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0mcell_order[0m[0;34m][0m[0;34m,[0m [0max[0m [0;34m=[0m [0max0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mmodelled_value[0m [0;34m=[0m [0mobserved[0m[0;34m.[0m[0msamples[0m[0;34m[[0m[0mobservation[0m[0;34m.[0m[0mp[0m[0;34m][0m[0;34m.[0m[0msel[0m[0;34m([0m[0msample[0m [0;34m=[0m [0;36m0[0m[0;34m)[0m[0;34m.[0m[0mto_pandas[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0msns[0m[0;34m.[0m[0mheatmap[0m[0;34m([0m[0mmodelled_value[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0mcell_order[0m[0;34m][0m[0;34m,[0m [0max[0m [0;34m=[0m [0max1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/projects/probabilistic-cell/latenta/src/latenta/posterior/samples.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m     57[0m [0;34m[0m[0m
[1;32m     58[0m     [0;32mdef[0m [0m__getitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 59[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_data[0m[0;34m[[0m[0mself[0m[0;34m.[0m[0m_map_key[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     60[0m [0;34m[0m[0m
[1;32m     61[0m     [0;32mdef[0m [0mkeys[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'H34rc9uV8AiEsdSY96iMTF'
KeyError: 'H34rc9uV8AiEsdSY96iMTF'

